name: date_bloc
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.0
  shared_preferences: ^0.5.7+3
  flutter_bloc: ^4.0.1
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3
  flutter_cupertino_date_picker: ^1.0.26+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  # lint: ^1.1.1
  bloc_test: ^5.0.0
flutter:

  
  
  
  uses-material-design: true

  
  #
